import { UsersSeeders } from "./user.types";
import { rolesSeeder } from "../roles/roles.seeder";
import { hashPasswordSync } from "../../auth/utils/bycript";
import { fakerUsers } from "../../faker/faker";

export const usersSeeder: UsersSeeders[] = [
  {
    id: "cllimozdc0001wr3swh067x93",
    firstname: "cristian",
    lastname: "jimenez",
    address: "cra 118b",
    phone: "5234",
    email: "cj@test.com",
    age: 29,
    password: hashPasswordSync("1234"),
    isActive: true,
    roleId: rolesSeeder[0].id,
  },
  {
    id: "cllimozdc0002wr3swh067x93",
    firstname: "rodrigo",
    lastname: "bonilla",
    address: "cll 100",
    phone: "9876",
    email: "rb@test.com",
    age: 22,
    password: hashPasswordSync("1234"),
    isActive: true,
    roleId: rolesSeeder[0].id,
  },
  {
    id: "cllimozdc0003wr3swh067x93",
    firstname: "jesus",
    lastname: "bravo",
    address: "cll 200",
    phone: "6543",
    email: "jb@test.com",
    age: 30,
    password: hashPasswordSync("1234"),
    isActive: true,
    roleId: rolesSeeder[0].id,
  },
  {
    id: "cllimozdc0004wr3swh067x93",
    firstname: "john",
    lastname: "due",
    address: "cll 7",
    phone: "8754",
    email: "jd@test.com",
    age: 30,
    password: hashPasswordSync("1234"),
    isActive: true,
    roleId: rolesSeeder[2].id,
  },
  {
    id: "cllimozdc0005wr3swh067x93",
    firstname: "jane",
    lastname: "due",
    address: "cll 8",
    phone: "3456",
    email: "jjd@test.com",
    age: 35,
    password: hashPasswordSync("1234"),
    isActive: true,
    roleId: rolesSeeder[2].id,
  },
  {
    id: "cllimozdc0006wr3swh067x93",
    firstname: "jason",
    lastname: "due",
    address: "cll 5",
    phone: "2665",
    email: "jdd@test.com",
    age: 25,
    password: hashPasswordSync("1234"),
    isActive: true,
    roleId: rolesSeeder[2].id,
  },
  ...fakerUsers,
];
